[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chronochat"
version = "0.1.0"
description = "A local chat CLI utility"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "telethon",
    "python-dotenv",
    "questionary"
]

[project.scripts]
chronochat = "main:main"

[tool.setuptools]
py-modules = ["auth", "config", "metadata", "cli", "main", "db"]
